apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: orderservice
  name: orderservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderservice
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: orderservice
    spec:
      containers:
      - image: soa/orderservice
        name: orderservice
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: orderservice
  name: orderservice
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: orderservice
  type: ClusterIP
status:
  loadBalancer: {}
